### ISSUE TITLE
[Feature request] Chain Setting values in session

### ISSUE THREAD

**Issue by joicemjoseph** [vividvilla/simplesessions#17]
It will be great to have a feature to set values to a session, like the following.

```
sess, _ := session.Aquire(...,...)
err := sess.Set('key1', 'value1').Set('key2', 'value2')...Commit()
```

If this sounds good, I can add this feature.

**Comment by knadh** [comment]
Do you mean a chainable shorthand instead of the current:
```go
sess, _ := session.Aquire(...,...)
sess.Set('key1', 'value1')
sess.Set('key2', 'value2')
sess.Commit()
```

**Comment by joicemjoseph** [comment]
> Do you mean a chainable shorthand instead of the current:

Yes.

**Comment by vividvilla** [comment]
This lib doesn't use chain pattern so the ideal API would be `SetMulti(arg1, val1, ...)`. @joicemjoseph If you are interested then send a PR.

**Comment by joicemjoseph** [comment]
I will raise a PR.
